CREATE TABLE IF NOT EXISTS reminders (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    appointment_id BIGINT NOT NULL REFERENCES appointments (id) ON DELETE CASCADE,
    send_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(20) NOT NULL CHECK (
        status IN ('QUEUED', 'SENT', 'FAILED')
    ) DEFAULT 'QUEUED',
    channel VARCHAR(20) NOT NULL CHECK (
        channel IN ('SMS', 'WHATSAPP', 'EMAIL')
    ),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP 
);